- hosts: all
  name: Configure server
  user: vagrant
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    ssh_users:
      - system_user: "{{ ansible_ssh_user }}"
        github_users:
          - winescout
          - smcfarlane
          - orangewolf
          - dewey4iv
          - adamthayer
    project_name: "{{ project_name }}"
    project_owner: "{{ project_owner }}"
    git_repo_url: "https://github.com/{{ project_owner }}/{{ project_name }}.git"
    git_repo_branch: "{{ project_version }}"
    cap_deployment: "{{ cap_deployment }}"
    solr_fqdn: "{{ solr_fqdn }}"
    solr_cores:
      - ident: "{{ project_name }}"
        type: "hyrax"
    tomcat_applications:
      - app_name: "fedora"
        shut_port: "8008"
        conn_port: "8080"
        rproxy_path: "fcrepo"
    mysql_databases:
      - name: "fedora"
        collation: "utf8_bin"
        encoding: "utf8"
        state: "present"
      - name: "{{ project_name }}"
        collation: "utf8_bin"
        encoding: "utf8"
        state: "present"
      - name: "{{ project_name }}-test"
        collation: "utf8_bin"
        encoding: "utf8"
        state: "present"
    mysql_users:
      - name: "{{ fcdb_user }}"
        host: "localhost"
        password: "{{ fcdb_password }}"
        priv: "fedora.*:ALL"
        state: "present"
      - name: "{{ samvera_db_user }}"
        host: "%"
        password: "{{ samvera_db_password }}"
        priv: "{{ project_name }}.*:ALL/{{ project_name }}-test.*:ALL"
        state: "present"
    fedora_db_user: "{{ fcdb_user }}"
    fedora_db_password: "{{ fcdb_password }}"
    fedora_db_host: "localhost"
    fedora_db_port: "3306"
    fedora_db_name: "fedora"
    fedora_admin_user: "{{ fc_admin_user }}"
    fedora_admin_password: "{{ fc_admin_password }}"
    fedora_server_fqdn: "localhost"
  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_samvera_basepackages }
    - { role: uclalib_role_java, oracle_java_version: '1.8.0_191' }
    - { role: uclalib_role_clamav }
    - { role: uclalib_role_pip }
    - { role: uclalib_role_imagemagick }
    - { role: uclalib_role_libreoffice, libreoffice_version: '6.0.7' }
    - { role: uclalib_role_ffmpeg, ffmpeg_download_url: 'https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.0.3-64bit-static.tar.xz' }
    - { role: uclalib_role_fits, fits_version: '1.3.0' }
    - { role: uclalib_role_ruby, ruby_version: '2.5.1' }
    - { role: uclalib_role_nodejs, nodejs_version: '8' }
    - { role: uclalib_role_yarn }
  tasks:
    - name: set up N8 ssh keys
      authorized_key: >
        user="{{ item.0.system_user }}"
        key="https://github.com/{{ item.1 }}.keys"
      with_subelements:
        - github_users
